### PR TITLE
Removed core-js

### PR DESCRIPTION
**Pull request by stevieing**
Closes #

Changes proposed in this pull request:

*
*
* ...

### CODE REVIEW

**Comment by stevieing** [comment]
This will need to be deployed from branch to see if there are any side effects.

**Review by BenTopping — APPROVED** [review]
Had a brief look into core-js and it serves as a js polyfill (supports new js features on unsupported browsers). It's not apparent how we used it (maybe when we used babel?). 
Happy to approve as I can't see any issues.

**Comment by stevieing** [comment]
That was my conclusion. I think it was left over from when we used babel.

I plan to install it from branch just to check that everything still works.

On 27 Feb 2023, at 12:02, Ben Topping ***@***.******@***.***>> wrote:



@BenTopping approved this pull request.

Had a brief look into core-js and it serves as a js polyfill (supports new js features on unsupported browsers). It's not apparent how we used it (maybe when we used babel?).
Happy to approve as I can't see any issues.

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sanger_traction-2Dui_pull_1076-23pullrequestreview-2D1315445242&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=PioAYl_Zz9lnGwJRms8MsEB0E-grNRW-ut-_gAGl70g&m=ziI5ZSZ2FDMo9cOOqUEttPl5zF4IBfepr72jHu_rSsG41pVcSg37V20CleGXYC17&s=xO6A93XEL0-CIFQOxK-QFd9oyhwMXXyFUOKMO0aoqto&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AAD6ZH7GBLHMFWKMV2FGXJLWZSJXFANCNFSM6AAAAAAVC3ZCXU&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=PioAYl_Zz9lnGwJRms8MsEB0E-grNRW-ut-_gAGl70g&m=ziI5ZSZ2FDMo9cOOqUEttPl5zF4IBfepr72jHu_rSsG41pVcSg37V20CleGXYC17&s=1wlgCDXz5PAJVvVOZWCM83z2uRV-BvI0BgqCJbtTTxg&e=>.
You are receiving this because you authored the thread.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by BenTopping** [comment]
@stevieing Tested thoroughly locally going through the entire pacbio pipeline. Seems good to go. Will get it on UAT with some other stuff which will inadvertently test it.

**Pull request merged**
