### PR TITLE
Gpl 322 dashboard refactor

### PR DESCRIPTION
**Pull request by harrietc52**
- Added ONT to Dashboard
- Tried to make Dashboard bit 'prettier'
- Along with refactor, trying to make use of vue components
- Using local storage instead of store to store pipeline state, so it persists over pages. Might be a nicer way to handle localStorage, wanted to prioritise completing the story.

### CODE REVIEW

**Comment by harrietc52** [comment]
- I Don't mind, I thought this may feel less clunky and more the default UX behaviour to handle returning back to the home page. Can add 'Dashboard' back in the nav bar if you think?  
- Didn't relise this was a requested feature. Just thought as we add more pipelines the Dashboard would get more clunky with lots of buttons. Again, can add back if you think? 
- Hm not sure what to do about this one. Maybe one for another story to look into how to reduce the UI? For libraries, now the samples are in the extra details, we could remove that column? Or start playing around with the css.

**Comment by stevieing** [comment]
How about this:
- for now add the links back into the boxes
- I will add a story to do some UX work with our customers. Happy to make that a priority as it is becoming an issue and we are second guessing so need some input.
Does that sound reasonable?

**Comment by harrietc52** [comment]
Yep that sounds good, 👍 thanks

**Comment by harrietc52** [comment]
Closes #304

**Comment by BenTopping** [comment]
It is not immediately obvious which pipeline you are looking at when on any given table, maybe adding a header declaring the pipeline would make it clearer. As Steve said, tables spill over (known on chrome) when tables are resized.

**Comment by harrietc52** [comment]
Updated:
- Added the pipeline to all the pipeline views so it is obvious what the user is in
- Made all tables scrollable, horizontally, to help spilling tables and improve UX

**Comment by harrietc52** [comment]
Failing as something in Travis has changed. SS etc effected too

**Pull request merged**
